name: "✨ Feature request"
description: "Suggest a new feature or improvement"
title: "[Feature Request]: "
type: feature
labels: ["enhancement", "no-priority"]

body:
  # Introductory Markdown
  - type: markdown
    attributes:
      value: |
        **Thank you for suggesting a new feature or improvement**

        Before creating a request, please:

        1. Search existing **open and closed** feature requests to avoid duplicates.
        1. Note that **repeat feature requests** are permitted if a previous request was closed more than 30 days ago.
        1. Consider implementing the feature yourself
        1. Feature requests that lack sufficient detail or feasibility may be closed at any time.
        1. Any request that is detrimental to security or the product’s stability will be closed without notice.

  # Checkboxes for Confirmations
  - type: checkboxes
    id: confirmations
    attributes:
      label: "Please confirm:"
      description: "Check all boxes that apply."
      options:
        - label: "**I have searched existing feature requests** (open and closed) and found no duplicates."
          required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: "Problem Statement"
      description: |
        **What problem does this feature solve or what gap does it fill?**  
        Provide a concise explanation. For example:
        - "When I need to enable MFA for all users, it takes a lot of time to do it per user. I'd like to enable this for all users in button press"
        - "To update a user property for exchange I need to go through 5 portals and 2 systems to be able to make a change."
    validations:
      required: true

  # Field 2: Benefits for MSPs
  - type: textarea
    id: msp-benefits
    attributes:
      label: "Benefits of Feature"
      description: |
        **How would this feature help MSPs or contributors**  
        - Does it reduce manual work?  
        - Does it improve security or scalability?  
        - Does it offer clarity or automation to commonly repeated tasks?
    validations:
      required: true

  # Field 3: Value or Importance
  - type: textarea
    id: feature-value
    attributes:
      label: "Value or Importance"
      description: |
        **Why is this feature particularly valuable or important to add?**  
        - If it's critical, explain why.  
        - If it's optional or nice-to-have, describe how it still adds notable value.
    validations:
      required: true
